/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_reeson2003_asm_AsmFunctions */

#ifndef _Included_ru_reeson2003_asm_AsmFunctions
#define _Included_ru_reeson2003_asm_AsmFunctions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_reeson2003_asm_AsmFunctions
 * Method:    asm_string_length
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_reeson2003_asm_AsmFunctions_asm_1string_1length
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_reeson2003_asm_AsmFunctions
 * Method:    asm_index_of
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ru_reeson2003_asm_AsmFunctions_asm_1index_1of
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ru_reeson2003_asm_AsmFunctions
 * Method:    asm_substring
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_reeson2003_asm_AsmFunctions_asm_1substring
  (JNIEnv *, jobject, jstring, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
